"""Add unique constraint to TaskOutput for idempotent writes

Revision ID: 009380d2cc74
Revises: 60eda0cec3f1
Create Date: 2025-09-26 08:36:24.891209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009380d2cc74'
down_revision = '60eda0cec3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_outputs', schema=None) as batch_op:
        batch_op.alter_column('local_path',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_unique_constraint('uq_task_node_fileurl', ['task_id', 'node_id', 'file_url'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('task_outputs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_node_fileurl', type_='unique')
        batch_op.alter_column('local_path',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
