"""add name field to task_outputs table

Revision ID: 91ffabddd0da
Revises: 5bf87319f0e2
Create Date: 2025-09-12 22:24:00.290953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ffabddd0da'
down_revision = '5bf87319f0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add nullable name column
    with op.batch_alter_table('task_outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
    
    # Step 2: Update existing records with file names extracted from local_path
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE task_outputs 
        SET name = CASE 
            WHEN local_path LIKE '%/%' THEN 
                substr(local_path, length(local_path) - length(replace(local_path, '/', '')) + 2)
            WHEN local_path LIKE '%\\%' THEN 
                substr(local_path, length(local_path) - length(replace(local_path, '\\', '')) + 2)
            ELSE local_path
        END
        WHERE name IS NULL
    """))
    
    # Step 3: Make name column NOT NULL
    with op.batch_alter_table('task_outputs', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_outputs', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
